on: pull_request
permissions:
  contents: write
jobs:
  update:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: |
        python3 setup.py install
        pip3 install jupyter --user
        jupyter nbconvert --execute --to notebook --inplace test.ipynb
        git config --global user.email "just4now666666@gmail.com"
        git config --global user.name "donno2048"
        git add .
        git commit -m "update notebook"
        git push origin HEAD:${{ github.head_ref }}
