on: pull_request
permissions:
  contents: write
jobs:
  update-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: '${{ github.head_ref }}'
    - uses: actions/setup-python@v3
    - run: |
        python3 -m pip install -U pip setuptools
        python3 setup.py install
        pip3 install jupyter --user
        jupyter nbconvert --execute --to notebook --inplace test-windows.ipynb
    - uses: actions/upload-artifact@v3
      with:
        path: test-windows.ipynb
  update-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: '${{ github.head_ref }}'
    - uses: actions/setup-python@v3
    - run: |
        python3 -m pip install -U pip setuptools
        python3 setup.py install
        pip3 install jupyter --user
        jupyter nbconvert --execute --to notebook --inplace test-linux.ipynb
    - uses: actions/upload-artifact@v3
      with:
        path: test-linux.ipynb
  commit:
    runs-on: ubuntu-latest 
    needs: [update-linux, update-windows]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v2
    - run: |
        git config --global user.email "just4now666666@gmail.com"
        git config --global user.name "donno2048"
        git add .
        git commit -m "update notebook"
        git push origin HEAD:${{ github.head_ref }}

