on: pull_request
permissions:
  contents: write
jobs:
  update:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: '${{ github.head_ref }}'
    - uses: actions/setup-python@v3
    - run: |
        python3 -m pip install -U pip setuptools
        python3 setup.py install
        pip3 install jupyter --user
        jupyter nbconvert --execute --to notebook --inplace test-${os,,}.ipynb
        mv test-${os,,}.ipynb ${{ runner.temp }}
      env:
        os: ${{ runner.os }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: "${{ runner.temp }}/*"
  commit:
    runs-on: ubuntu-latest
    needs: update
    steps:
    - uses: actions/checkout@v4
      with:
        ref: '${{ github.head_ref }}'
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - run: |
        git config --global user.email "just4now666666@gmail.com"
        git config --global user.name "donno2048"
        git add .
        git commit -m "update notebook"
        git push origin HEAD:${{ github.head_ref }}

